### PR TITLE
feat: support cloning sets and maps

### LINKED ISSUE #17: Support for Map and Set types
I would love to see support added for the native [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) types.

They are becoming increasingly popular and I use them all the time. But the current behavior when cloning them is to return an empty object:

```javascript
const data = {
    set: new Set([1, 2, 3]),
    map: new Map([
        ["a", 1],
        ["b", 2],
        ["c", 3]
    ])
};
console.log(data); // {set: {1, 2, 3}, map: {"a" => 1, "b" => 2, "c" => 3}}
console.log(clone(data)); // {set: {}, map: {}}
```

### PR DESCRIPTION
**Pull request by JammSpread**
Adds deep cloning functionality for objects of type Set and Map.
Fixes #17.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by JammSpread** [comment]
Should `Symbol.iterator` be checked for and cloned if possible? This wouldn't be copying *all* the symbol properties (#12) necessarily.  This would allow support for iterables in general.

**Comment by mcollina** [comment]
I would not copy non-enumerable properties. This is designed to be a fast replacement for `JSON.parse(JSON.stringify(o))`.

**Review by davidmarkclements — APPROVED** [review]
yeah okay, we're doing buffers and dates so we may as well do maps and sets

**Comment by davidmarkclements** [comment]
> I would not copy non-enumerable properties. This is designed to be a fast replacement for `JSON.parse(JSON.stringify(o))`.

agreed

**Comment by davidmarkclements** [comment]
thanks @JammSpread 4.3.0 released

**Pull request merged**
